name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Node.js dependencies
      run: npm ci

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build C++ components (Ubuntu/macOS)
      if: runner.os != 'Windows'
      run: make

    - name: Build C++ components (Windows)
      if: runner.os == 'Windows'
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        build_vs.bat
      shell: cmd

    - name: Run linter
      run: npm run lint
      continue-on-error: true

    - name: Run Node.js tests
      run: npm test

    - name: Run Python tests
      run: python -m pytest tests/
      continue-on-error: true

    - name: Run performance benchmarks
      run: python src/benchmark_assembler.py
      continue-on-error: true

    - name: Test MCP integration
      run: |
        timeout 10s node src/ultra_code_manager_enhanced.cjs || true
      shell: bash

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run security audit
      run: |
        npm audit --audit-level moderate
        pip install safety
        safety check

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        npm ci
        pip install -r requirements.txt

    - name: Build project
      run: |
        make
        npm run docs

    - name: Create release package
      run: |
        mkdir -p dist
        tar -czf dist/ultra-code-manager-enhanced-${{ github.sha }}.tar.gz \
          src/ docs/ examples/ \
          README.md LICENSE CHANGELOG.md INSTALL.md \
          package.json requirements.txt Makefile build_vs.bat

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ultra-code-manager-enhanced-${{ github.sha }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ultra-code-manager-enhanced-*/ultra-code-manager-enhanced-*.tar.gz
        body: |
          ## Ultra Code Manager Enhanced ${{ github.ref_name }}
          
          ### 🚀 Features
          - Advanced MCP server for code management
          - 17 powerful tools for file operations
          - Optimized performance (10x speedup)
          - Vector embeddings for semantic code search
          - Multi-level error protection and rollback
          
          ### 📦 Installation
          ```bash
          # Extract release
          tar -xzf ultra-code-manager-enhanced-*.tar.gz
          cd ultra-code-manager-enhanced
          
          # Install dependencies
          npm install
          pip install -r requirements.txt
          
          # Build C++ components
          make  # or build_vs.bat on Windows
          ```
          
          ### 🔧 Configuration
          See [INSTALL.md](INSTALL.md) for detailed setup instructions.
          
          ### 📖 Documentation
          - [README.md](README.md) - Overview and quick start
          - [DEVELOPER_GUIDE.md](docs/DEVELOPER_GUIDE.md) - Development guide
          - [API Examples](examples/) - Usage examples
          
          ### 🐛 Known Issues
          None reported for this release.
          
          ### 💝 Thanks
          Special thanks to all contributors and the MCP community!
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ultra-code-manager:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ultra-code-manager:${{ github.sha }}
        platforms: linux/amd64,linux/arm64